version: "3.9"

services:
  backend:
    build: ./backend
    container_name: phildle_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   # keeps your JWT_SECRET & DATABASE_URL safe
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: phildle_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: phildle_db
    env_file:
      - ./backend/.env   # load DB creds from the same .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: